spring.application.name=devshowcase-api

server.port=8080

# Banco H2 para desenvolvimento
spring.datasource.url=jdbc:h2:mem:devshowcase
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html

# Evita problemas com carregamento de relacionamentos fora da transação
spring.jpa.open-in-view=false